MarketPlaceCRM/MarketPlaceCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='main')),
    path('', include('products.urls', namespace='products')),
    path('', include('reports.urls', namespace='reports')),
    path('', include('shops.urls', namespace='shops')),
    path('profile/', include('UserProfile.urls', namespace='profile')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MarketPlaceCRM/UserProfile/urls.py
from django.urls import path
from .views import edit_profile, view_profile

app_name = 'profile'


urlpatterns = [
    path('edit/', edit_profile, name='edit_profile'),
    path('view/', view_profile, name='view_profile'),

]

MarketPlaceCRM/shops/urls.py
from django.urls import path
from .views import view_shop, edit_shops_card, add_shops, delete_shop


app_name = "shops"


urlpatterns = [
    path("view_shops/", view_shop, name="view_shops"),
    path("edit_shops/<int:id>/", edit_shops_card, name="edit_shops"),
    path("add_shops/", add_shops, name="add_shops"),
    path("delete_shop/<int:id>/", delete_shop, name="delete_shop"),
]

MarketPlaceCRM/templates/profile/edit_profile.html
{% extends "base.html" %} {% load static %} {% block content %}
<div class="content-wrapper" style="min-height: 2646.62px">
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Профиль</h1>
        </div>
      </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-9">
          <div class="card">
            <div class="card-body">           
                <div class="tab-pane active" id="settings">
                  <form action="" method="post" class="form-horizontal">
                    {% csrf_token %}

                    
                    <div class="form-group row">
                      <label for="inputName" class="col-sm-2 col-form-label"
                        >Имя</label>
                      <div class="col-sm-10">
                        {{ form.user_name }}
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label"
                          >Email</label>
                        <div class="col-sm-10">
                          {{ form.email }}
                        </div>
                      </div>
                    <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label"
                          >Telegram username</label>
                        <div class="col-sm-10">
                          {{ form.tg_username }}
                        </div>
                    </div>
                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <button type="submit" class="btn btn-danger">
                          Сохранить изменения
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

MarketPlaceCRM/templates/profile/view_profile.html
{% extends "base.html" %} {% load static %} {% block content %}
{% load custom_filters %}
<div class="content-wrapper" style="min-height: 2646.62px">
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Профиль</h1>
        </div>
      </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-9">
          <div class="card">
            <div class="card-body">           
                <div class="tab-pane active" id="settings">
                    <div class="form-group row">
                      <label for="inputName" class="col-sm-2 col-form-label"
                        >Имя</label>
                      <div class="col-sm-10">
                        <p>
                            {{ user }}
                        </p>
                      </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label"
                          >Email</label>
                        <div class="col-sm-10">
                          <p>
                              {{ user.profile.email }}
                          </p>
                        </div>
                      </div>
                    
                      
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label"
                          >Telegram username</label>
                        <div class="col-sm-10">
                          <p>
                              {{ user.profile.tg_username }}
                          </p>
                        </div>
                      </div>
                      
                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <a href="{% url 'profile:edit_profile' %}" class="btn btn-danger">Редактировать</a>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <a href="{% url 'shops:add_shops' %}" class="btn btn-primary">Добавить новый магазин</a>
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <a href="{% url 'shops:view_shops' %}" class="btn btn-info">Просмотреть мои магазины</a>
                      </div>
                    </div>

                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}