MarketPlaceCRM/MarketPlaceCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='main')),
    path('', include('products.urls', namespace='products')),
    path('', include('reports.urls', namespace='reports')),
    path('', include('shops.urls', namespace='shops')),
    path('profile/', include('UserProfile.urls', namespace='profile')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MarketPlaceCRM/reports/urls.py
from django.urls import path
from .views import generate_report, view_reports, save_report, view_report, download_report, delete_report


app_name = 'reports'


urlpatterns = [
    path('generate_report/', generate_report, name='generate_report'),
    path('view_reports/', view_reports, name='view_reports'),
    path('save_report/', save_report, name='save_report'),
    path('download/<int:report_id>/', download_report , name='download_report'),
    path('view_report/<int:report_id>/', view_report, name='view_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
]

MarketPlaceCRM/shops/urls.py
from django.urls import path
from .views import view_shop, edit_shops_card, add_shops, delete_shop


app_name = "shops"


urlpatterns = [
    path("view_shops/", view_shop, name="view_shops"),
    path("edit_shops/<int:id>/", edit_shops_card, name="edit_shops"),
    path("add_shops/", add_shops, name="add_shops"),
    path("delete_shop/<int:id>/", delete_shop, name="delete_shop"),
]

MarketPlaceCRM/reports/models.py
from django.db import models

from products.models import ProductCard
from django.contrib.auth.models import User


class Reports(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='Alex')
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d %H:%M:%S")  # Форматируем дату в строку


class Report(models.Model):
    rep = models.ForeignKey(Reports, on_delete=models.CASCADE, related_name='reports')
    product_name = models.CharField(max_length=255, verbose_name='name')
    price_uan = models.FloatField(default=0, verbose_name='price_uan')
    price_rub = models.FloatField(default=0, verbose_name='price_rub')
    product_weight = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='weight')
    product_quantity = models.IntegerField(default=0, verbose_name='quantity')
    delivery_in_china_uan = models.FloatField(default=0, verbose_name='delivery_in_china_uan')
    delivery_in_china_rub = models.FloatField(default=0, verbose_name='delivery_in_china_rub')
    commission_uan = models.FloatField(verbose_name='commission_uan')
    commission_rub = models.FloatField(verbose_name='commission_rub')
    delivery_to_moscow = models.FloatField(default=0, verbose_name='delivery_to_moscow')
    delivery_to_office = models.FloatField(default=0, verbose_name='delivery_to_office')
    last_insurance = models.FloatField(default=0, verbose_name='last_insurance')

    def __str__(self):
        return self.product_name



MarketPlaceCRM/reports/forms.py
from django import forms
from .models import Report
from django.forms import ModelForm, modelformset_factory


class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = ['product_name', 'price_uan',
                  'product_weight', 'product_quantity']
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя товара'}),
            'product_price': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Введите цену товара (в Юанях)'}),
            'product_weight': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Введите вес товара (в кг)'}),
            'product_quantity': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Введите кол-во товара'}),
        }


class ReportCardForm(ModelForm):
    class Meta:
        model = Report
        fields = [
            'product_name',
            'price_uan',
            'price_rub',
            'delivery_in_china_uan',
            'delivery_in_china_rub',
            'commission_uan',
            'commission_rub',
            'delivery_to_moscow',
            'delivery_to_office',
            'last_insurance'
        ]
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя товара'}),
            'price_uan': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Цена товара (в Юанях)'}),
            'price_rub': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Цена товара (в Рублях)'}),
            'delivery_in_china_uan': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Доставка до китая в юанях.'}),
            'delivery_in_china_rub': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Доставка до китая в рублях.'}),
            'commission_uan': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Комиссия в юанях.'}),
            'commission_rub': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Комиссия в рублях.'}),
            'delivery_to_moscow': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Доставка до Москвы'}),
            'delivery_to_office': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Доставка до офиса'}),
            'last_insurance': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Страховка'})
        }


ReportFormSet = modelformset_factory(Report, form=ReportCardForm, extra=0)

MarketPlaceCRM/reports/views.py
from pprint import pprint

from django.template import context
import pandas as pd
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from products.models import ProductCard
from .models import Report, Reports
from .forms import ReportFormSet
from products.views import view_products


@login_required
def generate_report(request):
    if request.method == 'POST':
        selected_items = request.POST.getlist('selected_items')
        selected_items_int = [int(item) for item in selected_items]  # Достаем из чекбоксов ID наших товаров и добавляем их в список
        # Фильтруем только те товары, которые принадлежат текущему пользователю
        selected_objects = ProductCard.objects.filter(id__in=selected_items_int, user=request.user)
        context = {
            'objects': selected_objects
        }

        return render(request, 'reports/generate_report.html', context)
    else:
        # Дополнительный код на случай GET-запроса, если требуется
        pass


@login_required
def save_report(request):
    if request.method == 'POST':
        price_prefix = 'product_price_'
        quantity_prefix = 'product_quantity_'
        name_prefix = 'product_name_'
        weight_prefix = 'product_weight_'
        delivery_prefix = 'delivery_in_china_'

        product_prices = {}
        product_quantities = {}
        product_names = {}
        product_weights = {}
        deliverys_in_china = {}

        try:
            for key in request.POST:
                if key.startswith(price_prefix):
                    product_id = key[len(price_prefix):]
                    product_prices[product_id] = float(request.POST[key].replace(',', '.'))
                elif key.startswith(quantity_prefix):
                    product_id = key[len(quantity_prefix):]
                    product_quantities[product_id] = int(request.POST[key])
                elif key.startswith(name_prefix):
                    product_id = key[len(name_prefix):]
                    product_names[product_id] = request.POST[key]
                elif key.startswith(weight_prefix):
                    product_id = key[len(weight_prefix):]
                    product_weights[product_id] = float(request.POST[key].replace(',', '.'))
                elif key.startswith(delivery_prefix):
                    product_id = key[len(delivery_prefix):]
                    deliverys_in_china[product_id] = float(request.POST[key].replace(',', '.'))
        except ValueError as e:
            return JsonResponse({'error': f'Неверный формат данных: {str(e)}'}, status=400)

        try:
            commission = float(request.POST.get('commission', '0').replace(',', '.'))
            commission_5_proc = {
                product_id: (product_prices[product_id]) * commission / 100
                for product_id in product_prices
            }
        except ValueError as e:
            return JsonResponse({'error': f'Неверная комиссия: {str(e)}'}, status=400)

        try:
            purchase_amount = sum(
                product_prices[product_id] * product_quantities[product_id]
                for product_id in product_prices
            )
        except ValueError as e:
            return JsonResponse({'error': f'Неверная сумма покупки: {str(e)}'}, status=400)

        total_weight = sum(
            product_weights.get(product_id, 0) * product_quantities.get(product_id, 0)
            for product_id in product_weights
        )

        try:
            delivery_office = float(request.POST.get('delivery_to_office', '0').replace(',', '.'))
            delivery_moscow = float(request.POST.get('delivery_to_moscow', '0').replace(',', '.'))
        except ValueError as e:
            return JsonResponse({'error': f'Неверная стоимость доставки в офис или Москву: {str(e)}'}, status=400)

        reports_instance = Reports.objects.create(user=request.user)  # Привязка отчета к пользователю

        for product_id in product_prices:
            try:
                insurance = float(request.POST.get('last_insurance', '0').replace(',', '.'))
                course_dollar = float(request.POST.get('price_dollar', 0))
                course_uan = float(request.POST.get('price_uan', 0))

                price_uan = product_prices[product_id]
                price_rub = price_uan * course_uan
                commission = commission_5_proc.get(product_id, 0)
                quantity = product_quantities.get(product_id, 0)
                weight = product_weights.get(product_id, 0)
                div_in_china = deliverys_in_china.get(product_id, 0) / quantity
                delivery_to_office_item = (weight * delivery_office) / total_weight if total_weight != 0 else 0
                delivery_to_moscow_item = (weight * delivery_moscow) / total_weight if total_weight != 0 else 0

                last_insurance = (price_rub + round(div_in_china * course_uan, 2) + commission * course_uan) * insurance / 100

                report_instance = Report(
                    rep=reports_instance,
                    product_name=product_names.get(product_id),
                    price_uan=price_uan,
                    price_rub=price_rub,
                    product_weight=weight,
                    product_quantity=quantity,
                    delivery_in_china_uan=round(div_in_china, 2),
                    delivery_in_china_rub=round(div_in_china, 2) * course_uan,
                    commission_uan=commission,
                    commission_rub=commission * course_uan,
                    delivery_to_moscow=delivery_to_moscow_item * course_dollar,
                    delivery_to_office=delivery_to_office_item,
                    last_insurance=last_insurance
                )
                report_instance.save()
            except ValueError as e:
                return JsonResponse({'error': f'Ошибка в расчетах: {str(e)}'}, status=400)

        return redirect('reports:view_reports')
    else:
        # Дополнительный код на случай GET-запроса, если требуется
        return render(request, 'reports/save_report.html')



@login_required
def view_reports(request):
    # Фильтрация отчетов текущего пользователя
    reports = Reports.objects.filter(user=request.user)

    # Фильтрация продуктов текущего пользователя
    products = ProductCard.objects.filter(user=request.user)

    #Проверка на наличие данных в базе
    if not reports.exists() or not products.exists():
        return redirect('products:view_products')

    context = {
        'reports': reports,
        'products': products
    }
    return render(request, 'reports/view_reports.html', context)


@login_required
def view_report(request, report_id):
    reports_instance = get_object_or_404(Reports, pk=report_id)
    reports = Report.objects.filter(rep=reports_instance)

    if request.method == 'POST':
        formset = ReportFormSet(request.POST, queryset=reports)
        if formset.is_valid():
            formset.save()
            return redirect('reports:view_report', report_id=report_id)
    else:
        formset = ReportFormSet(queryset=reports)

    titles = [
        'Название товара',
        "Цена в Юанях",
        "Цена в Рублях",
        "Доставка по Китаю в Юанях",
        "Доставка по Китаю в Рублях",
        "Комиссия в Юанях",
        "Комиссия в Рублях",
        "Доставка до Москвы",
        "Доставка до Офиса",
        "Страховка",
    ]

    context = {
        'formset': formset,
        'titles': titles,
        'reports': reports,
        'report_id': report_id,
        'report_instance': reports_instance,
    }

    return render(request, 'reports/view_report.html', context)


@login_required
def download_report(request, report_id):
    reports = Report.objects.filter(rep_id=report_id)

    data = []
    for report in reports:
        data.append([
            report.product_name, report.price_uan, report.price_rub,
            report.delivery_in_china_uan, report.delivery_in_china_rub,
            report.commission_uan, report.commission_rub,
            report.delivery_to_moscow, report.delivery_to_office,
            report.last_insurance
        ])

    df = pd.DataFrame(data,
                      columns=['Имя продукта', 'Цена за единицу товара (¥)', 'Цена за единицу товара (₽)',
                               'Доставка по Китаю (¥)', 'Доставка по Китаю (₽)', 'Комиссия (¥)', 'Комиссия (₽)',
                               'Доставка до МСК (₽)', 'Доставка до офиса (₽)', 'Страховка (₽)'])

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename=report_{report_id}.xlsx'

    with pd.ExcelWriter(response, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name='Sheet1')

    return response


@login_required
def delete_report(request, report_id):
    report_instance = get_object_or_404(Reports, id=report_id)
    report_instance.delete()
    return redirect('reports:view_reports')

MarketPlaceCRM/templates/reports/generate_report.html
{% extends "base.html" %}
{% load static %}



{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Отчет по выбранным товарам</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Детали отчета</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <!-- TITLE -->
                            <div class="row hide-on-small text-sm-center">
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center">Название товара</label>
                                </div>
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center">Цена товара</label>
                                </div>
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center">Вес товара</label>
                                </div>
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center">Количество товара</label>
                                </div>
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center">Доставка по Китаю</label>
                                </div>
                                <div class="col-md-2 d-flex align-items-center">
                                    <label class="w-100 text-center"></label>
                                </div>
                            </div>
                            <form action="{% url 'reports:save_report' %}" method="post">
                            {% csrf_token %}
                            {% for item in objects %}
                                <div class="row m-1">
                                    <div class="col-md-2">
                                        <div class="input-group mb-2">
                                            <input type="text" class="form-control" name="product_name_{{ item.id }}" value="{{ item.product_name }}" placeholder="Название">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group mb-2">
                                            <input type="text" class="form-control" name="product_price_{{ item.id }}" value="{{ item.product_price }}" placeholder="Цена ₽">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group mb-2">
                                            <input type="text" class="form-control" name="product_weight_{{ item.id }}" value="{{ item.product_weight }}" placeholder="Вес (в кг.)">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group mb-2">
                                            <input type="text" class="form-control" name="product_quantity_{{ item.id }}" value="{{ item.product_quantity }}" placeholder="Количество">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group mb-2">
                                            <input type="text" class="form-control" name="delivery_in_china_{{ item.id }}" value="{{ item.delivery_in_china }}" placeholder="Доставка по Китаю">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group mb-2"></div>
                                    </div>
                                </div>

                            {% endfor %}
                                <div class="row m-1">
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">$</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Доставка до МСК" name="delivery_to_moscow">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">%</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Комиссия" value="3" name="commission">
                                        </div>
                                    </div>
                                </div>
                                <div class="row m-1">
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">₽</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Доставка до офиса" name="delivery_to_office">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">%</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Страховка" value="1" name="last_insurance">
                                        </div>
                                    </div>
                                </div>
                                <div class="row m-1">
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">¥</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Курс Юаня" value="12" name="price_uan">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">$</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Курс Доллара" value="85" name="price_dollar">
                                        </div>
                                    </div>
                                </div>
                                <div class="m-3">
                                    <button type="submit" class="btn btn-primary">Сохранить отчет</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

MarketPlaceCRM/templates/reports/view_report.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="content-wrapper" style="min-height: 2646.62px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Отчеты</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title mb-2">Расчет за единицу</h3>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">
                        <form method="post">
                            {% csrf_token %}
                            {{ formset.management_form }}
                            <table class="table table-hover text-nowrap">
                                <thead>
                                    <tr>
                                        {% for title in titles %}
                                            <th> {{ title }} </th>
                                        {% endfor %}
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for form in formset %}
                                        <tr>
                                            {% for field in form %}
                                                <td>{{ field }}</td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}


                                </tbody>
                            </table>
                            <button class="btn btn-primary ml-2" type="submit">Обновить данные в БД</button>
                        </form>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="p-3 mb-2 text-white">
                                <form action="{% url 'reports:delete_report' report_id=report_instance.id %}" method="post"
                                    style="display:inline;">
                                    {% csrf_token %}
                                    <button class="btn btn-block btn-danger btn-lg" type="submit">Удалить отчет</button>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="p-3 mb-2 text-white">
                                <a class="btn btn-block btn-success btn-lg"
                                    href="{% url 'reports:download_report' report_id=report_instance.id %}">
                                    <i class="fas fa-download"></i> Скачать отчет
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        <!-- /.card-body -->

        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
{% endblock %}

MarketPlaceCRM/templates/reports/view_reports.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="content-wrapper" style="min-height: 2646.62px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Отчеты</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Расчет за единицу</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          №
                      </th>
                      <th style="width: 70%">
                          Дата отчета
                      </th>
                      <th style="width: 29%">
                      </th>
                  </tr>
              </thead>
              <tbody>
              {% for report in reports %}
                <tr>
                      <td>
                          {{ report.id }}
                      </td>
                      <td>
                          <a>
                              {{ report.date}}
                          </a>
                      </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="{% url 'reports:view_report' report_id=report.id %}">
                              <i class="fas fa-folder">
                              </i>
                              Посмотреть
                          </a>
                      </td>

                  </tr>
              {% endfor %}

              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock %}



