MarketPlaceCRM/MarketPlaceCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='main')),
    path('', include('products.urls', namespace='products')),
    path('', include('reports.urls', namespace='reports')),
    path('', include('shops.urls', namespace='shops')),
    path('profile/', include('UserProfile.urls', namespace='profile')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MarketPlaceCRM/UserProfile/urls.py
from django.urls import path
from .views import edit_profile, view_profile

app_name = 'profile'


urlpatterns = [
    path('edit/', edit_profile, name='edit_profile'),
    path('view/', view_profile, name='view_profile'),

]

MarketPlaceCRM/homepage/urls.py
from django.urls import path
from .views import login_request, logout_view, homepage, telegram_login

app_name = 'main'

urlpatterns = [
    path('', login_request, name='login'),  # Страница входа через форму
    path('homepage/', homepage, name='homepage'),  # Домашняя страница
    path('logout/', logout_view, name='logout'),  # Выход из системы
    path('telegram/login/', telegram_login, name='telegram_login'),  # Вход через Telegram
]

MarketPlaceCRM/products/urls.py
from django.urls import path
from .views import add_product_from_csv, add_product_alone, edit_product_card, delete_product, view_products, add_product


app_name = 'products'


urlpatterns = [
    path('add_product/', add_product, name='add_product'),
    path('add_product_alone/', add_product_alone, name='add_product_alone'),
    path('add_product_from_csv/', add_product_from_csv, name='add_product_from_csv'),
    path('view_products/', view_products, name='view_products'),
    path('edit_product/<int:id>/', edit_product_card, name='edit_product'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
]

MarketPlaceCRM/reports/urls.py
from django.urls import path
from .views import generate_report, view_reports, save_report, view_report, download_report, delete_report


app_name = 'reports'


urlpatterns = [
    path('generate_report/', generate_report, name='generate_report'),
    path('view_reports/', view_reports, name='view_reports'),
    path('save_report/', save_report, name='save_report'),
    path('download/<int:report_id>/', download_report , name='download_report'),
    path('view_report/<int:report_id>/', view_report, name='view_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
]

MarketPlaceCRM/shops/urls.py
from django.urls import path
from .views import view_shop, edit_shops_card, add_shops, delete_shop


app_name = "shops"


urlpatterns = [
    path("view_shops/", view_shop, name="view_shops"),
    path("edit_shops/<int:id>/", edit_shops_card, name="edit_shops"),
    path("add_shops/", add_shops, name="add_shops"),
    path("delete_shop/<int:id>/", delete_shop, name="delete_shop"),
]

MarketPlaceCRM/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WB | Ozon AdminPanel</title>

  <link rel="stylesheet" href="/static/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dist/css/myset.css' %}">
  <link rel="stylesheet" href="{% static 'assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <style>
        /* Скрыть элемент на экранах шириной менее 768px */
        @media (max-width: 767px) {
            .hide-on-small {
                display: none;
            }
        }
  </style>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{% static 'assets/dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->

  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'main:homepage' %}" class="brand-link">
      <img src="{% static 'assets/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Market Place CRM</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="flex-direction: column; align-items: center; justify-content: center;">
        <a href="{% url 'profile:view_profile' %}">
            <div class="image" style="display: block;">
                <img src="{% static 'assets/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info" style="display: block;">
                <span class="d-block">{{ request.user.username }}</span>
            </div>
        </a>
        <div class="logout">
          <a href="{% url 'main:logout' %}" class="btn btn-primary btn-block"><b>Выйти</b></a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            
          {% if request.user.is_authenticated and request.user.is_superuser %}
           <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p>Админ-панель</p>
            </a>
          </li>
          {% endif %}

          
          <li class="nav-item">
            <a href="{% url 'products:add_product' %}" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
              <p>Добавить товар в БД</p>
            </a>
          </li>

            <li class="nav-item">
                <a href="{% url 'products:view_products' %}" class="nav-link">
                  <i class="nav-icon fas fa-book"></i>
                  <p>Посмотреть все товары</p>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'reports:view_reports' %}" class="nav-link">
                  <i class="nav-icon fas fa-table"></i>
                  <p>Посмотреть отчеты</p>
                </a>
            </li>


        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->

    {% block content %}

    {% endblock content %}
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2024.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

  <!-- Control Sidebar -->

  <!-- /.control-sidebar -->
</div>


<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<script src="{% static 'assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'assets/dist/js/adminlte.js' %}"></script>
{% block scripts %}
{% endblock scripts %}

</body>
</html>