MarketPlaceCRM/MarketPlaceCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='main')),
    path('', include('products.urls', namespace='products')),
    path('', include('reports.urls', namespace='reports')),
    path('', include('shops.urls', namespace='shops')),
    path('profile/', include('UserProfile.urls', namespace='profile')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MarketPlaceCRM/products/urls.py
from django.urls import path
from .views import add_product_from_csv, add_product_alone, edit_product_card, delete_product, view_products, add_product


app_name = 'products'


urlpatterns = [
    path('add_product/', add_product, name='add_product'),
    path('add_product_alone/', add_product_alone, name='add_product_alone'),
    path('add_product_from_csv/', add_product_from_csv, name='add_product_from_csv'),
    path('view_products/', view_products, name='view_products'),
    path('edit_product/<int:id>/', edit_product_card, name='edit_product'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
]

MarketPlaceCRM/reports/urls.py
from django.urls import path
from .views import generate_report, view_reports, save_report, view_report, download_report, delete_report


app_name = 'reports'


urlpatterns = [
    path('generate_report/', generate_report, name='generate_report'),
    path('view_reports/', view_reports, name='view_reports'),
    path('save_report/', save_report, name='save_report'),
    path('download/<int:report_id>/', download_report , name='download_report'),
    path('view_report/<int:report_id>/', view_report, name='view_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
]

MarketPlaceCRM/shops/urls.py
from django.urls import path
from .views import view_shop, edit_shops_card, add_shops, delete_shop


app_name = "shops"


urlpatterns = [
    path("view_shops/", view_shop, name="view_shops"),
    path("edit_shops/<int:id>/", edit_shops_card, name="edit_shops"),
    path("add_shops/", add_shops, name="add_shops"),
    path("delete_shop/<int:id>/", delete_shop, name="delete_shop"),
]

MarketPlaceCRM/products/models.py
from django.db import models
from django.contrib.auth.models import User


class ProductCard(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.TextField(
        max_length=200, unique=True, verbose_name='Имя товара')
    product_price = models.FloatField(verbose_name='Цена товара')
    product_weight = models.FloatField(verbose_name='Вес товара')
    delivery_in_china = models.FloatField(verbose_name='Доставка по Китаю', default=0)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product_card'

MarketPlaceCRM/products/forms.py
from django import forms
from .models import ProductCard
from django.forms import ModelForm


class ProductCardForm(ModelForm):
    class Meta:
        model = ProductCard
        fields = ['product_name', 'product_price', 'product_weight']
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя товара'}),
            'product_price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Введите цену товара (в Юанях)'}),
            'product_weight': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Введите вес товара (в кг)'}),
            # 'product_quantity': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Количество товара'}),
        }


class UploadCSVForm(forms.Form):
    csv_file = forms.FileField()

MarketPlaceCRM/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
import csv
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .forms import UploadCSVForm, ProductCardForm
from .models import ProductCard


@login_required
def add_product(request):
    return render(request, 'products/add_product.html')

@login_required
def add_product_alone(request):
    if request.method == 'POST':
        form = ProductCardForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect('products:view_products')
    else:
        form = ProductCardForm()
    return render(request, 'products/add_product_alone.html', {'form': form})



@login_required
def add_product_from_csv(request):
    if request.method == 'POST':
        form = UploadCSVForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = form.cleaned_data['csv_file']
            csv_content = csv_file.read().decode('utf-8-sig')
            reader = csv.DictReader(csv_content.splitlines(), delimiter=';')

            # Обработка данных
            for row in reader:
                name = row.get('Артикул', '').strip('"').strip("'")
                price = row.get('Текущая цена с учетом скидки, ₽', '').strip('"').strip("'")
                weight = row.get('Объемный вес, кг', '').strip('"').strip("'")

                # Замена запятой на точку для корректного преобразования в float
                price = price.replace(',', '.')
                weight = weight.replace(',', '.')
                
                

                # Проверка наличия всех необходимых полей
                if name and price and weight:
                    try:
                        price = float(price)  # Преобразуем цену в число с плавающей точкой
                        weight = float(weight)  # Преобразуем вес в число с плавающей точкой
                    except ValueError:
                        messages.warning(request, f'Неверные данные в строке: {row}')
                        continue

                    # Проверяем, существует ли уже товар с таким названием
                    user = request.user
                    if not ProductCard.objects.filter(product_name=name).exists():
                        ProductCard.objects.create(
                            user=user,
                            product_name=name,
                            product_price=price,
                            product_weight=weight
                        )
                else:
                    messages.warning(request, f'Недостаточные данные в строке: {row}')
                    print('Недостаточно данных в строке')
                    
            messages.success(request, 'Товары успешно добавлены.')
            return redirect(reverse('products:view_products'))
    else:
        form = UploadCSVForm()
        print(form.errors)
        
    return render(request, 'products/add_product_from_csv.html', {'form': form})



@login_required
def view_products(request):
    all_products = ProductCard.objects.filter(user=request.user)
    column_names = ['Выбрать объект', 'Имя товара', 'Цена товара', 'Вес товара']
    
    if not all_products.exists():
        return redirect('products:add_product')

    context = {
        'products': all_products,
        'column_names': column_names
    }
    return render(request, 'products/view_products.html', context)


@login_required
def edit_product_card(request, id):
    product = get_object_or_404(ProductCard, pk=id)
    if request.method == "POST":
        form = ProductCardForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            # Перенаправляем на страницу со списком товаров после успешного редактирования
            return redirect('products:view_products')
    else:
        form = ProductCardForm(instance=product)
    return render(request, 'products/edit_product.html', {'form': form, 'data': product})

@login_required
def delete_product(request, id):
    product = get_object_or_404(ProductCard, pk=id)
    if request.method == 'POST':
        product.delete()
        return redirect('products:view_products')
    return render(request, 'products/delete_product.html', {'product': product})




MarketPlaceCRM/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}



  {% block content %}
  <div class="content-wrapper" style="min-height: 273px;">

    <section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
    <div class="col-sm-6">
    <h1>Добавить товар в БД</h1>
    </div>
    <div class="col-sm-6">
    </div>
    </div>
    </div>
    </section>
    
    <section class="content">
    
    <div class="card">
    <div class="card-header">
    <h3 class="card-title">Выбири способ добавления товара</h3>
    <div class="card-tools">
    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
    <i class="fas fa-minus"></i>
    </button>
    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
    <i class="fas fa-times"></i>
    </button>
    </div>
    </div>
    <div class="card-body" style="display: block;">
      <div class="row">
        <div class="col-md-2">
          <a href="{% url 'products:add_product_alone' %}" class="btn btn-block btn-primary btn-sm">Добавить один товар</a>
        </div>
        <div class="col-md-2">
          <a href="{% url 'products:add_product_from_csv' %}" class="btn btn-block btn-success btn-sm">Добавить из файла .csv</a>
        </div>
      </div>
    </div>
    
    
    </div>
    
    </section>
    
    </div>
  {% endblock content %}



MarketPlaceCRM/templates/products/add_product_alone.html
{% extends "base.html" %}
{% load static %}



  {% block content %}
    <div class="content-wrapper" style="min-height: 1302.12px;">
    <!-- Content Header (Page header) -->

    


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
        <!-- /.row -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Добавить товар в БД</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{% url 'products:add_product_alone' %}" method="post">
                {% csrf_token %}
                <div class="card-body">
                  
                  <div class="form-group">
                    <label for="exampleInputText">Товар</label>
                    {{ form.product_name }}
                  </div>
                  <div class="form-group">
                    <label for="exampleInputText">Цена в юанях</label>
                    {{ form.product_price }}
                  </div>
                  <div class="form-group">
                    <label for="exampleInputText">Вес товара (в кг)</label>
                    {{ form.product_weight }}
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
              </form>
                
            <!-- /.card -->


          </div>
      </div><!-- /.container-fluid -->
      
    </section>
    <!-- /.content -->
    </div>
  {% endblock content %}



MarketPlaceCRM/templates/products/add_product_from_csv.html
{% extends "base.html" %}
{% load static %}



  {% block content %}
  <div class="content-wrapper" style="min-height: 273px;">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Добавить товары из файла .csv</h1>
          </div>
          <div class="col-sm-6"></div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Загрузить файл</h3>
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Загрузить</button>
          </form>
        </div>
      </div>
    </section>
  </div>
  {% endblock %}

MarketPlaceCRM/templates/products/delete_product.html
{% extends "base.html" %}
{% load static %}



  {% block content %}
    <div class="content-wrapper" style="min-height: 1302.12px;">
    <!-- Content Header (Page header) -->

    


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
        <!-- /.row -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="callout callout-info">
              <h5><i class="fas fa-info"></i> Внимание:</h5>
              Вы уверены, что хотите удалить товар "{{ product.product_name }}"?
              <form action="{% url 'products:delete_product' id=product.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm" type="submit">Да, удалить</button>
                <a href="{% url 'products:view_products' %}">Отмена</a>
            </form>
            </div>
      </div><!-- /.container-fluid -->
      
    </section>
    <!-- /.content -->
    </div>
  {% endblock content %}


MarketPlaceCRM/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}



  {% block content %}
    <div class="content-wrapper" style="min-height: 1302.12px;">
    <!-- Content Header (Page header) -->

    


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
        <!-- /.row -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Изменить карточку товара</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="" method="post">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputText">Товар</label>
                    {{ form.product_name }}
                  </div>
                  <div class="form-group">
                    <label for="exampleInputText">Цена в юанях</label>
                    {{ form.product_price }}
                  </div>
                  <div class="form-group">
                    <label for="exampleInputText">Вес товара (в кг)</label>
                    {{ form.product_weight }}
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Внести изменения</button>
                  <a href="{% url 'products:delete_product' id=data.id %}" class="btn btn-danger">Удалить</a>
                </div>
              </form>
            <!-- /.card -->


          </div>
      </div><!-- /.container-fluid -->
      
    </section>
    <!-- /.content -->
    </div>
  {% endblock content %}



MarketPlaceCRM/templates/products/view_products.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <!-- Main content -->
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Товары</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Свернуть">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Удалить">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <form action="{% url 'reports:generate_report' %}" method="post">
                    {% csrf_token %}
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                {% for column_name in column_names %}
                                <th>{{ column_name }}</th>
                                {% endfor %}
                                <th>Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                <td style="width: 1%" data-field="checkbox">
                                    <input class="m-2" type="checkbox" name="selected_items" value="{{ product.id }}">
                                </td>
                                <td data-field="name">{{ product.product_name }}</td>
                                <td data-field="price">{{ product.product_price }}</td>
                                <td data-field="weight">{{ product.product_weight }}</td>
                                <td>
                                    <a class="btn btn-warning btn-xs" href="{% url 'products:edit_product' product.id %}">
                                        <i class="fas fa-pencil-alt"></i> Изменить
                                    </a>
                                    <a class="btn btn-danger btn-xs" href="{% url 'products:delete_product' product.id %}">
                                        <i class="fas fa-trash"></i> Удалить
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="m-2">
                        <button type="submit" class="btn btn-primary">Сформировать закупку</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
{% endblock content %}